criação e definição da entidades a serem persistidas
felipemandu/manga-app-study pull request #1
Opened 2021-04-23 17:55 UTC by felipemandu

Criação das entidades que representam o modelo para persistencia em um banco relacional, por enquanto persistido em ambiente dev no banco em memory h2.

2021-04-26 14:01 UTC, vmoliveira-uol requested changes
Deixei alguns reviews que julgo ser importantes. Comentei em alguns pontos apenas, mas algumas situações se repetem ao longo do código.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Author.kt
> +import javax.persistence.*
Como boa prática, evitamos imports com **. Você pode alterar isso nas configurações da IDE em:
File > Settings > Editor > Code Style > Kotlin
Nos campos "Use import with '*' when at least" mantenha sempre o maior valor. Isso impedirá os imports dessa forma.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Author.kt
> +class Author(
Classes entity no Kotlin são do tipo data class

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Author.kt
> +        @Column(name = "author_id")
Vi que você mapeou a coluna, está correto. Mas você não mapeou a qual tabela se refere. Então a coluna é author_id, mas de qual tabela? Isso acarretará em erro.
Outra dica: mantenha o nome das colunas em caixa alta, facilita a quem lê identificar o que é coluna e o que é parâmetro.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Author.kt
> +        var name: String,
A coluna id você maperou, mas essa e as demais não. Elas não existem na tabela? Não entendi.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Country.kt
> +        var name:String,
Em usou apenas variáveis do tipo "var". Utilize val.
Em Kotlin, val indica um parâmetro como final. Você pode criar a princípio como val e ir alterando para var a medida que for sendo necessário.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Manga.kt
> +                joinColumns = [JoinColumn(name = "manga_id")],
Não entendi, você está fazendo join com a coluna manga_id E com a author_id?
O ideal é manter apenas uma chave estrangeira para cada tabela. Mais que isso, você pode ter problemas.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Manga.kt
> +        var originLanguage: Language?,
Você indicou que esse parâmetro pode ser nulo (em kotlin, o character "?" indica isso), mas indicou a coluna no banco como não-nula. Isso vai gerar um problemão.
Ou a coluna é nula ou não é. Para contornar esse problema ou você muda ou define um valor default.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Status.kt
> +    HIATUS("hiatus"), COMPLETED("completed"), ONGOING("ongoing")
Formata essa classe. A classe LanguageEnum.kt você aplicou a formatação, mas não nessa.
Isso facilita a quem está fazendo o review da PR além de manter um padrão no código.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Chapter.kt
> +class Chapter (
Você criou várias classes Entity, mas nenhuma Repository. O ideal é que sempre que você criar uma entity, na sequência crie a classe repository referente ao objeto a ser salvo no banco. Cria com o básico e caso faça-se necessário, você vai acrescentando as demais querys conforme a demanda.
Dessa forma você já consegue subir a aplicação local e testar se está tudo funcional e/ou criar casos de teste.

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Source.kt
> +class Source (
Dúvida: O que seria essa classe Source?

2021-04-26 14:01 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Source.kt
> +        return "Source(name='$name')"
Para o toString, o legal seria você colocar o máximo de informações possíveis. Assim você poderia usá-lo para fins de log.

2021-04-26 14:26 UTC, felipemandu commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Author.kt
> +        var name: String,
Então, provavelmente você não trabalham assim, e isso é bom saber. 
Eu pensei numa abordagem code first para o db. então, pelo menos na primeira vez, a app subiria  e criaria o db. Nesse sentindo  os nomes das colunas seriam automaticamente gerados pelo nome da variável, Devido a isso eu mapiei apenas o id  para um nome de coluna especifico  para aumentar a semantica das queries:
exemplo: SELECT m FROM Manga m JOIN Author a ON a.author_id  = :authorId WHERE m.translated_language = :translatedLanguage
 ao invés de  SELECT m FROM Manga m JOIN Author a ON a.id  = :authorId WHERE m.translated_language = :translatedLanguage
 
 
 Então o correto seria criar o db, através do sql e depois mapear as classes para as colunas?

2021-04-26 14:30 UTC, felipemandu commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Source.kt
> +class Source (
aquela aplicação que eu mandei para vocês é tipo agregador de fornacedor de mangas. Nesse sentindo, esse source seria um como um site onde os mangas são hospedados, assim o mesmo manga, pode ser hospedado em um fonte diferente, sendo uma entidade diferente, pois poderia ter outra tradução (outro grupo traduziu), outra scan, ou qualidade e etc.  
Eu realmente não sei como nomear isso.

2021-04-26 14:32 UTC, felipemandu commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Source.kt
> +        return "Source(name='$name')"
Legal, essa parte do log eu realmente nunca fiz. Então eu não sei quais são as práticas.  Eu gerei o toString apenas para facilitar algum debugger em dev. Quais seriam campos relevantes neste caso? todos? ou existe alguma abordagem para isso?

2021-04-26 14:36 UTC, felipemandu commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Manga.kt
> +        var originLanguage: Language?,
foi milho mesmo, Eu parti de uma abordagem, depois mudei no meio do caminho, mas sobrou uma interrogação ali.

2021-04-26 15:51 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Author.kt
> +        var name: String,
Sim, quando partimos para a criação da entidade, já temos definida a tabela e seus campos. Nós criamos via script de migration, mas não é algo que você deva se preocupar com isso no momento.
A ideia é começar bem de baixo mesmo, primeiro a criação da tabela no banco com suas estidades e na sequência a entity e o repository. Sua ideia é boa, mas não funciona pra gente porque não temos autonomia pra criar em prod. Apenas via script.

2021-04-26 15:52 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Source.kt
> +class Source (
Entendi.

2021-04-26 15:56 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Source.kt
> +        return "Source(name='$name')"
Isso você quem define. Mas a ideia do log é você colocar as informações que te auxiliem caso algum problema ocorra e você precise identificar qual registro ocasionou o erro. Por exemplo neste caso, só pelo nome você conseguiria identificar qual é o registro? Tem de ser dados que te facilitem numa ação rápida.

2021-04-26 18:33 UTC, felipemandu commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Manga.kt
> +                joinColumns = [JoinColumn(name = "manga_id")],
Então, na verdade eu to criando uma tabela de relacionamento muitos para muitos. a tabela tem o nome manga_autor
Nessa tabela teriam apenas os id de cada entidade (manga_id, author_id), assim partindo de um manga, com um id, iriamos na tabela e pegariamos todos os id de autores que tem relação com aquele manga.

2021-04-26 21:27 UTC, felipemandu commented
@vmoliveira-uol Depois que eu criei o script, eu não estava conseguindo mapear daquela forma que conversamos no slack. 
Eu cheguei a olha e vi que no pscore tem umas entidades com @ManyToMany mapeadas daquela maneira. Por enquanto deixei do jeito que estava para estar buildando, usando o joinTable. Pretendo continuar tentando alterar isso.

2021-04-29 16:16 UTC, vmoliveira-uol commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Chapter.kt
> +    val pages: Set<String>,
Dúvida: eu vi que existe esse campo Pages e ali em cima tem um Number_Pages. Qual a ideia da diferença entre elas?

2021-04-29 16:46 UTC, felipemandu commented on src/main/kotlin/felipemandu/com/br/mangaappstudy/entity/Chapter.kt
> +    val pages: Set<String>,
Eu considerei por exemplo que os arquivos (os jpg das paginas) estão salvos em algum local, e o que esta salvo nesse db seria apenas as strings com os endereços. 
assim esse pages seria uma lista desse endereços: e o valor ali de cima seria a quantidades de paginas.

Os dois não são necessariamente iguais. Por exemplo, um manga pode n paginas, mas na horas de scannear algumas imagens foram unidas ou separadas. O que leva que exista um numero diferente de imagens do que o número real de páginas.

2021-04-29 17:15 UTC, vmoliveira-uol approved these changes

2021-04-29 18:23 UTC, matheusmessora approved these changes

2021-04-29 18:28 UTC, merged